name: Terraform CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.9"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Configure AWS Credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::984774734569:role/aws-lab-github-terraform-role
          aws-region: ap-northeast-1
          allowed-account-ids: "984774734569"

      - name: Verify AWS Identity
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: aws sts get-caller-identity

      - name: Terraform Init - Remote State
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: terraform init

      - name: Terraform Init - No Backend
        if: github.event_name == 'pull_request'
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: terraform plan

  terraform_apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: terraform
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.9"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::984774734569:role/aws-lab-github-terraform-apply-role
          aws-region: ap-northeast-1
          allowed-account-ids: "984774734569"

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
